version: '3'

services:

  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    env_file:
      - .env

  librespot:
    build: ./librespot
    restart: always
    network_mode: host
    privileged: true
    env_file:
      - .env

  snapclient:
    build:
      context: ./snapclient
      args:
        SNAPCAST_VERSION: 0.20.0
    restart: always
    network_mode: host
    privileged: true
    env_file:
      - .env
