services:
  pulseaudio:
    image: clcain/pulseaudio
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/snd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - ./default.pa:/etc/pulse/default.pa:ro
    command: >
      pulseaudio --exit-idle-time=-1 --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1"

  librespot:
    image: clcain/librespot
    restart: unless-stopped
    network_mode: host
    depends_on:
      - pulseaudio
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PULSE_SERVER=tcp:localhost:4713
    env_file:
      - .env

  shairport-sync:
    image: clcain/shairport-sync
    restart: unless-stopped
    network_mode: host
    depends_on:
      - pulseaudio
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PULSE_SERVER=tcp:localhost:4713
    env_file:
      - .env
    entrypoint: /init
    command: ["/run.sh", "-o", "pa", "-a", "${DEVICE_NAME}"]

  snapclient:
    image: clcain/snapclient
    restart: unless-stopped
    network_mode: host
    depends_on:
      - pulseaudio
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PULSE_SERVER=tcp:localhost:4713
    env_file:
      - .env
