version: '3'

services:

  librespot:
    image: clcain/librespot
    restart: unless-stopped
    network_mode: host
    privileged: true
    env_file:
      - .env

  shairport-sync:
    image: clcain/shairport-sync
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    env_file:
      - .env

  snapclient:
    image: clcain/snapclient
    restart: unless-stopped
    network_mode: host
    privileged: true
    env_file:
      - .env
